<a href="https://colab.research.google.com/github/Kum007/AIcourse/blob/main/EDAex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
titanic_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv')
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic_data.isna().sum()
titanic_data['PassengerId'].value_counts()

In [ ]:
titanic_data.shape

NameError: name 'titanic_data' is not defined

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
titanic_data.shape

NameError: name 'titanic_data' is not defined

In [ ]:
titanic_data['Fare'].isna().sum()
titanic_data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [12]:
import numpy as np
arr=np.arange(25)
arr=np.reshape(arr,(5,5))

In [15]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [26]:
arr[1::2,0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])